# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Propag25
                                 A QGIS plugin
 A wildfire simulator
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-14
        copyright            : (C) 2025 by Alberto Valverde
        email                : alberto@toscat.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Propag25 class from file Propag25.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .propag25 import Propag25
    return Propag25(iface)
