[package]
name = "py-propag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_propag"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
