[package]
name = "firelib-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
const_soft_float = "0.1.4"
heapless = "0.8.0"
lazy_static = "1.5.0"
rand = "0.9.0"
uom = "0.36.0"

[dev-dependencies]
firelib-sys = { path = "../firelib-sys" }
quickcheck = "1.0.3"

[features]
default = ["std"]
std = []
