[package]
name = "behave-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
uom = "0.36.0"

[dev-dependencies]
firelib-sys = { path = "../firelib-sys" }
quickcheck = "1.0.3"
