name: "Test"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: https://nixcache.toscat.net/
        cache: propag25
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Build everything
      run: nix run .#buildAll --accept-flake-config
    - name: Run checks
      run: nix flake check
